version: '3'
services:
  alexanderjamesking:
    build: .
    image: alexanderjamesking/alexanderjamesking:latest
    restart: always
    ports:
      - "3000:3000"
    container_name: alexanderjamesking
